name: MoneyBlocks
author: Fridious
description: Get money on block break with a specified chance.
version: ${project.version}
main: de.fridious.moneyblocks.MoneyBlocks
softdepend:
- Vault
commands:
  moneyblocks: